# Specifies the Docker Compose file format version.
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:8000"
    volumes:
      - .:/app
    # This line tells Compose to load variables from the .env file
    env_file:
      - .env